'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import Header from './header';
import Footer from './footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'KakaoBoards-web',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
        <head>
            <title>KakaoBoards</title>
            <link href='/charactor_01.ico' rel='short icon' type='image/x-icon'></link>
        </head>
        <body className={inter.className}>
            <Header/>
            {children}
            <Footer/>
        </body>
    </html>
  )
}